
=pod

=head1 Задачи по курсу "Криптопротоколы"

=head2  ГОСТ 34.10-94 получение подписи

Файл - ./1/sign.asm. Написан под 64х битный Linux.
Требуется perl модуль Digest::GOST, который используется для получения хеша из
ГОСТ 34.11-94.
    
    # install Digest::GOST
    sudo cpan Digest::GOST

    # Compile && link
    nasm -f elf64 sign.asm -o sign.o && ld sign.o -o sign

    # Run
    perl -e 'use Digest::GOST qw(gost); print gost("This is message, length=32 bytes")' | ./sign

=head2 Шифрование с закладкой

Файл - ./2/crypt.pl. Требуются модули Crypt::Blowfish, Digest::MD5.

    sudo cpan Crypt::Blowfish Digest::MD5
    
    # normal encode
    cat text2.txt | ./crypt.pl -e password | ./crypt.pl -d password
    
    # bit ivertation
    cat text.txt  | ./crypt.pl -e password | ./crypt.pl -d password

=head2 Шифрование с бэкдором

Файл - ./3/crypt.pl. Требуются модули Crypt::Blowfish, Digest::MD5.
То же самое, что и в предыдущей задаче, но следим за появлением скрытого файла '.off'

=head2 Безопасная игра

Файлы: ./4/server.pl и ./4/client.pl. Все модули должны быть уже установлены.
Запускаем сначала сервер, потом клиента. Игра в морской бой. С вероятностью 0.5
клиент пытается обмануть. Игра - упрощённый аналог морского боя.

=head2 Широковщательная передача сообщений

Файлы: ./5/*.pl - 3 пользователя. Расширяется до n добавлением ключей в массив @S.
Передача - через файл share.dat.

    # Дать возможность прочитать сообщение всем, кроме 2ого
    $ perl ./1.pl write
    2: hello world!

    # Читаем сообщение
    $ perl ./3.pl read
    2: hello world!

    # Запрет чтения для 2ого и 3его
    $ perl ./1.pl write
    2,3: hello world!


